# Generated by Django 5.2.8 on 2025-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
